Howard_Mann/week_05/day_03/dragoon/config/routes.rb
Rails.application.routes.draw do

  root 'races#index'
  resources :races
  resources :characters
  resources :units
  resources :weapons
  resources :homeworlds

end

Howard_Mann/week_05/day_03/dragoon/app/models/character.rb
# == Schema Information
#
# Table name: characters
#
#  id         :integer          not null, primary key
#  name       :string
#  image      :text
#  background :text
#  race_id    :integer
#  weapon_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Character < ActiveRecord::Base
  belongs_to :race
  belongs_to :weapon
end

Howard_Mann/week_05/day_03/dragoon/app/models/homeworld.rb
class Homeworld < ActiveRecord::Base
  has_and_belongs_to_many :races
end

Howard_Mann/week_05/day_03/dragoon/app/models/race.rb
# == Schema Information
#
# Table name: races
#
#  id          :integer          not null, primary key
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image       :text
#  homeworld   :text
#  description :text
#  leader      :text
#

class Race < ActiveRecord::Base
  has_many :units
  has_many :weapons, :through => :units
  has_many :characters
  has_and_belongs_to_many :homeworlds
end

Howard_Mann/week_05/day_03/dragoon/app/models/unit.rb
# == Schema Information
#
# Table name: units
#
#  id         :integer          not null, primary key
#  name       :string
#  race_id    :integer
#  weapon_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Unit < ActiveRecord::Base
  belongs_to :race
  belongs_to :weapon
end

Howard_Mann/week_05/day_03/dragoon/app/models/weapon.rb
# == Schema Information
#
# Table name: weapons
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Weapon < ActiveRecord::Base
  has_many :units
  has_many :characters
  has_many :races, :through => :units
  has_many :races, :through => :characters
end

Howard_Mann/week_05/day_03/dragoon/app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
  end

  def show
    @character = Character.find_by(:name => params[:id])
  end

  def new
    @character = Character.new
  end

  def create
    character = Character.create(character_params )
    if character.save
      redirect_to characters_path
    else
      render :new
    end
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    character = Character.find(params[:id])
    character.update( character_params )
    redirect_to character_path( character.name )
  end

  def destroy
    character = Character.find(params[:id])
    character.destroy
    redirect_to characters_path
  end

  private
    def character_params
      params.require(:character).permit(:name, :image, :background, :race_id, :weapon_id)
    end
end

Howard_Mann/week_05/day_03/dragoon/app/controllers/homeworlds_controller.rb
class HomeworldsController < ApplicationController
  def index
    @homeworlds = Homeworld.all
  end

  def show
    @homeworld = Homeworld.find_by(:name => params[:id])
  end

  def edit
  end

  def new
  end
end

Howard_Mann/week_05/day_03/dragoon/app/controllers/races_controller.rb
class RacesController < ApplicationController
  def index
    @races = Race.all
  end

  def show
    @race = Race.find_by(:name => params[:id])
  end

  def new
    @race = Race.new
  end

  def create
    race = Race.create( race_params )
    if race.save
      redirect_to races_path
    else
      render :new
    end
  end

  def edit
    @race = Race.find(params[:id])
  end

  def update
    race = Race.find(params[:id])
    race.update( race_params )
    redirect_to race_path( race.name )
  end

  def destroy
    race = Race.find(params[:id])
    race.destroy
    redirect_to races_path
  end

  private
    def race_params
      params.require(:race).permit(:name, :image, :homeworld, :description, :leader)
    end
end

Howard_Mann/week_05/day_03/dragoon/app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index
    @units = Unit.all
  end

  def show
    @unit = Unit.find_by(:name => params[:id])
  end

  def new
    @unit = Unit.new
  end

  def create
    unit = Unit.create(unit_params)
    if unit.save
      redirect_to units_path
    else
      render :new
    end
  end

  def edit
    @unit = Unit.find(params[:id])
  end

  def update
    unit = Unit.find(params[:id])
    unit.update( unit_params )
    redirect_to unit_path( unit.name )
  end

  private
    def unit_params
      params.require(:unit).permit(:name, :image, :race_id, :weapon_id)
    end
end

Howard_Mann/week_05/day_03/dragoon/app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  def index
    @weapons = Weapon.all
  end

  def show
    @weapon = Weapon.find_by(:name => params[:id])
  end

end

Howard_Mann/week_05/day_03/dragoon/app/helpers/characters_helper.rb
module CharactersHelper
end

Howard_Mann/week_05/day_03/dragoon/app/helpers/homeworlds_helper.rb
module HomeworldsHelper
end

Howard_Mann/week_05/day_03/dragoon/app/helpers/races_helper.rb
module RacesHelper
end

Howard_Mann/week_05/day_03/dragoon/app/helpers/units_helper.rb
module UnitsHelper
end

Howard_Mann/week_05/day_03/dragoon/app/helpers/weapons_helper.rb
module WeaponsHelper
end

Howard_Mann/week_05/day_03/dragoon/app/views/homeworlds/edit.html.erb
<h1>Homeworlds#edit</h1>
<p>Find me in app/views/homeworlds/edit.html.erb</p>

Howard_Mann/week_05/day_03/dragoon/app/views/homeworlds/index.html.erb
<h1>Homeworlds</h1>

<ul>
  <% @homeworlds.each do |el| %>
    <li><%= link_to el.name, homeworld_path(el.name) %></li>
  <% end %>
</ul>

Howard_Mann/week_05/day_03/dragoon/app/views/homeworlds/new.html.erb
<h1>Homeworlds#new</h1>
<p>Find me in app/views/homeworlds/new.html.erb</p>

Howard_Mann/week_05/day_03/dragoon/app/views/homeworlds/show.html.erb
<h1>Homeworld: <%= @homeworld.name %></h1>

<p>Races occupying planet:</p>
<ul>
  <% @homeworld.races.each do |el|  %>
    <li><%= link_to el.name, race_path(el.name) %></li>
  <% end %>
</ul>

Howard_Mann/week_05/day_03/dragoon/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dragoon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <h1>Starcraft Wiki</h1>
  <nav>
    <div class="left-nav">
      <%= link_to 'Races', races_path %> |
      <%= link_to 'Homeworlds', homeworlds_path %> |
      <%= link_to 'Units', units_path %> |
      <%= link_to 'Heroes', characters_path %> |
      <%= link_to 'Weapons', weapons_path %>
    </div>
    <div class="right-nav">
      <%= link_to 'New Race', new_race_path %> |
      <%= link_to 'New Units', new_unit_path %> |
      <%= link_to 'New Hero', new_character_path %>
    </div>
  </nav>
  </header>
  <hr>
  <div class="container clearfix">
    <%= yield %>
  </div>
  <hr>

</body>
</html>