Howard_Mann/week_05/day_05/users_and_sessions/config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'session#new', :as => 'login'
  post '/login' => 'session#login'
  delete '/logout' => 'session#logout', :as => 'logout'

  root 'session#new'
  resources :users
  resources :projects

end

Howard_Mann/week_05/day_05/users_and_sessions/app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
end

Howard_Mann/week_05/day_05/users_and_sessions/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :projects
end

Howard_Mann/week_05/day_05/users_and_sessions/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :fetch_user

  private
    def fetch_user
      unless @current_user.present?
        session[:user_id] = nil
      end

      if session[:user_id]
        @current_user = User.find(session[:user_id])
      end

    end
end

Howard_Mann/week_05/day_05/users_and_sessions/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end
end

Howard_Mann/week_05/day_05/users_and_sessions/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def login
    user = User.find_by(:email => params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = "Login unsuccessful"
      redirect_to login_path
    end
  end

  def logout
    user = User.find(session[:user_id])
    session[:user_id] = nil
    flash[:success] = "#{user.name} succesfully logged out"
    redirect_to login_path
  end
end

Howard_Mann/week_05/day_05/users_and_sessions/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_admin, :only => [:index]
  # Only admin is authorized to see all users (index page)

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    user = User.create( user_params )
    if user.save
      redirect_to user_path( user )
    else
      render :new
    end
  end

  def edit
    if @current_user.present? && @current_user.admin
      @user = User.find(params[:id])
    elsif @current_user.present? && @current_user.admin == false
      @user = @current_user
    else
      flash[:error] = "Don't even think about it"
      redirect_to login_path
    end
  end

  def update
    user = User.find( params[:id] )
    user.update( user_params )
    redirect_to user_path( user )
  end

  def destroy
    user = User.find( params[:id] )
    user.destroy
    redirect_to users_path
  end

  private
    def user_params
      params.require( :user ).permit(:name, :email, :password, :password_confirmation, :admin)
    end

    def authorize_admin
      unless @current_user.present? && @current_user.admin
        flash[:error] = "You are not authorized to view that, only admin is"
        redirect_to login_path
      end
    end
end

Howard_Mann/week_05/day_05/users_and_sessions/app/helpers/projects_helper.rb
module ProjectsHelper
end

Howard_Mann/week_05/day_05/users_and_sessions/app/helpers/session_helper.rb
module SessionHelper
end

Howard_Mann/week_05/day_05/users_and_sessions/app/helpers/users_helper.rb
module UsersHelper
end

Howard_Mann/week_05/day_05/users_and_sessions/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UsersAndSessions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <% if @current_user.present? && @current_user.admin %>
      <%= link_to 'Admin All Users', users_path %><br>
    <% end %>

    <%= link_to 'All Projects', projects_path %>
    <%= link_to 'New User', new_user_path %><br>

    <% unless @current_user.present? %>
      <%= link_to 'Login', login_path %>
    <% end %>

    <% if @current_user.present? %>
      <%= link_to "Log out", logout_path, :method => :delete %>
    <% end %>

    <% if @current_user.present? %>
      <%= link_to "User profile", user_path(@current_user) %>
    <% end %>

  </nav>

  <!-- FLASH MESSAGES -->
  <% if session[:user_id] %>
    <p><%= User.find(session[:user_id]).name%> logged in</p>
  <% end %>

  <% if flash[:success] %>
    <p style="color: green"><%= flash[:success] %></p>
  <% end %>

  <% if flash[:error] %>
    <p style="color: red"><%= flash[:error] %></p>
  <% end %>
  <!-- FLASH MESSAGES -->

<%= yield %>

</body>
</html>

Howard_Mann/week_05/day_05/users_and_sessions/app/views/projects/index.html.erb
<h1>All projects</h1>
<ul>
  <% @projects.each do |el|  %>
    <li><%= link_to el.name, project_path(el) %></li>
  <% end %>
</ul>

Howard_Mann/week_05/day_05/users_and_sessions/app/views/projects/show.html.erb
<h1>Project show: <%= @project.name %></h1>
<p>Project user: <%= link_to @project.user.name, user_path(@project.user) %></p>