Yangmei_Chen/week_05/day_02/book_app/config/routes.rb
Rails.application.routes.draw do
  resources :authors, :books
end

Yangmei_Chen/week_05/day_02/book_app/app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
end

Yangmei_Chen/week_05/day_02/book_app/app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
end

Yangmei_Chen/week_05/day_02/book_app/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find params[:id]
  end

  def new
    @author = Author.new
  end

  def create
    author = Author.create(author_params)
    redirect_to authors_path
  end

  def edit
    @author = Author.find params[:id]
  end

  def update
    author = Author.find params[:id]
    author.update author_params
    redirect_to author_path
  end

  def destroy
    author = Author.find params[:id]
    author.destroy
    redirect_to authors_path
  end

  private
  def author_params
    params.require(:author).permit(:name, :image, :dob, :nationality, :books)
  end

end

Yangmei_Chen/week_05/day_02/book_app/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find params[:id]
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.create(book_params)
    redirect_to books_path
  end

  def edit
    @book = Book.find params[:id]
  end

  def update
    book = Book.find params[:id]
    book.update book_params
    redirect_to book_path
  end

  def destroy
    book = Book.find params[:id]
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :image, :publish_date, :page_count, :author_id)
  end
end

Yangmei_Chen/week_05/day_02/book_app/app/helpers/authors_helper.rb
module AuthorsHelper
end

Yangmei_Chen/week_05/day_02/book_app/app/helpers/books_helper.rb
module BooksHelper
end

Yangmei_Chen/week_05/day_02/book_app/app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, :required => true %>
  </p>
  <p>
    <%= f.label :nationality %>
    <%= f.text_field :nationality, :required => true %>
  </p>
  <p>
    <%= f.label :dob, "Date of Birth" %>
    <%= f.date_field :dob, :required => true %>
  </p>
  <p>
    <%= f.label :image %>
    <%= f.url_field :image, :required => true %>
  </p>
  <%= f.submit %>
<% end %>

Yangmei_Chen/week_05/day_02/book_app/app/views/authors/edit.html.erb
<h1>Edit the Author Here</h1>

<%= render :partial => 'form' %>

Yangmei_Chen/week_05/day_02/book_app/app/views/authors/index.html.erb
<h1>All Authors</h1>

<ul>
  <% @authors.each do |author| %>
    <li>
      <%= image_tag(author.image) %>
      <ul>
        <li>Name: <%= link_to(author.name, author_path(author)) %></li>
        <li>Nationality: <%= author.nationality %></li>
        <li>Date of Birth: <%= author.dob %></li>
        <hr>
      </ul>
    </li>
  <% end %>
</ul>

Yangmei_Chen/week_05/day_02/book_app/app/views/authors/new.html.erb
<h1>Create a New Author Here</h1>


<%= render :partial => 'form' %>

Yangmei_Chen/week_05/day_02/book_app/app/views/authors/show.html.erb
<h1>Author Information</h1>

<h2><%= @author.name %></h2>
<%= image_tag( @author.image ) %>
<p>
  Nationality: <%= @author.nationality %>
</p>
<p>
  Date of Birth: <%= @author.dob %>
</p>

<div class="controls">
  <!-- Edit and delete links go here -->
  <%= link_to "Edit this Author", edit_author_path( @author.id ) %>
  <%= link_to "Delete this Author", @author, :method => :delete, :data => { :confirm => "Are you sure?" } %>
</div>

<hr>

<h3>Books:</h3>
<ul>
  <% @author.books.each do |book| %>
    <li><%= link_to( book.title, book_path ) %></li>
  <% end %>
</ul>